### PR TITLE
Add integration test

### PR DESCRIPTION
**Pull request by mikaelkalt**
Resolves issues #17 - Created an integration test that start the matching against two nodes which are started in a docker container.

### CODE REVIEW

**Comment by MarkusTiede** [comment]
When invoking
```
MarkusTiede:openprevo opencode$ pwd
/Users/opencode/git/github/open-prevo/openprevo

MarkusTiede:openprevo opencode$ docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q) && docker rmi -f $(docker images -q)

MarkusTiede:openprevo opencode$ ./gradlew clean build && docker-compose build && docker-compose up
```

I reproducibly get a 404:
```
hub_1            | 2018-07-03 13:57:59.780 DEBUG 1 --- [pool-1-thread-1] ch.prevo.open.hub.HubScheduler           : Start matching task
hub_1            | 2018-07-03 13:57:59.798 ERROR 1 --- [pool-1-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
hub_1            | 
hub_1            | org.springframework.web.client.HttpClientErrorException: 404 Not Found
hub_1            | 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
hub_1            | 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
hub_1            | 	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
hub_1            | 	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:766) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
hub_1            | 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:724) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
hub_1            | 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:680) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
hub_1            | 	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:332) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
hub_1            | 	at ch.prevo.open.hub.nodes.NodeService.lookupInsurantInformationList(NodeService.java:47) ~[classes!/:na]
hub_1            | 	at ch.prevo.open.hub.nodes.NodeService.getCurrentEntries(NodeService.java:41) ~[classes!/:na]
hub_1            | 	at ch.prevo.open.hub.HubService.matchAndNotify(HubService.java:28) ~[classes!/:na]
hub_1            | 	at ch.prevo.open.hub.HubScheduler.run(HubScheduler.java:23) ~[classes!/:na]
hub_1            | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
hub_1            | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
hub_1            | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
hub_1            | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
hub_1            | 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
hub_1            | 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
hub_1            | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
hub_1            | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_171]
hub_1            | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_171]
hub_1            | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_171]
hub_1            | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
hub_1            | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
hub_1            | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
```

**Comment by mikaelkalt** [comment]
@MarkusTiede thanks for the hint - fixed the base url for the docker nodes.

**Comment by MarkusTiede** [comment]
@mikaelkalt : could you please resolve the master merge conflicts first?

**Comment by mikaelkalt** [comment]
Yeah sure, I‘m actually waiting for the dummy adapter - so I don’t have to do the work twice. Should be fixed tomorrow morning

**Pull request merged**
