### PR TITLE
Register shutdown hook to avoid potential resource leak

### LINKED ISSUE #107: Resource leak: 'context' is never closed / Proper application context / bean shutdown
## Summary / Zusammenfassung

2 IDE warnings: Resource leak: 'context' is never closed

## Success Criteria / Abnahmekriterien: leaks have been resolved
  1. Description	Resource	Path	Location	Type
Resource leak: 'context' is never closed	DBProviderFactory.java	/adapter-example-spring/src/main/java/org/example/prevo/open/adapter	line 19	Java Problem
  1. Description	Resource	Path	Location	Type
Resource leak: 'context' is never closed	PaktDBProviderFactory.java	/adapter-pakt/src/main/java/ch/prevo/pakt	line 19	Java Problem

### PR DESCRIPTION
**Pull request by MarkusTiede**
Fixes #107

### CODE REVIEW

**Comment by netopyr** [comment]
If you define the ApplicationContext as a Singleton, you are entering a pretty dangerous path.

The correct fix IMO would be to define a shutdown-hook, that closes the context. This would not fix the supposed potential resource leak (which is not a problem IMO anyway), but it would make sure that the context shuts down gracefully.

**Comment by MarkusTiede** [comment]
Agreeing: having a shutdown hook would be even better (and closing [is recommended](https://stackoverflow.com/questions/14184059/spring-applicationcontext-resource-leak-context-is-never-closed)); however: this PR ensures that the context is not instantiated multiple times - the application context itself is not a singleton; only its wrapper.

You can, if you want, still create multiple instances when explicitly using the constructor. But it's (imho) ensured that the SPI mechanism won't create multiple instances.

I guess you´d recommend adding a suppress warning?

**Comment by netopyr** [comment]
Well, I'd recommend to add the shutdown hook. I can imagine that some resources require this to flush cached data or something.

Maybe this removes the warning already (IntelliJ does not show me a warning, thus I cannot check). Otherwise we should ignore it.

**Comment by mikaelkalt** [comment]
👍 if @netopyr agrees we could merge that one?

**Comment by netopyr** [comment]
Well, I don't agree. ;) But I do not want to block it either.

**Comment by mikaelkalt** [comment]
ok after talking to @netopyr I agree that it is dangerous to create the application context as singleton because now it can be consumed from everywhere, which should definitely not be the case. 
In addition, it is also not a problem if it is instantiated multiple times. That's a programming error than.

**Pull request merged**
